/*
	Copyright 2023 Mohamed Shalan

	Author: Mohamed Shalan (mshalan@aucegypt.edu)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define CRM0_BASE				0x00000000

#define	CRM0_MUX_CTRL_REG_ADDR		(CRM0_BASE+0x0)
#define	CRM0_CLK_DIV_REG_ADDR		(CRM0_BASE+0x4)
#define	CRM0_ROSC_DIV_REG_ADDR		(CRM0_BASE+0x8)

#define CRM0_MUX_CTRL_REG_SEL_MUX0		0
#define CRM0_MUX_CTRL_REG_SEL_MUX0_LEN	1
#define CRM0_MUX_CTRL_REG_SEL_MUX1		1
#define CRM0_MUX_CTRL_REG_SEL_MUX1_LEN	1
#define CRM0_MUX_CTRL_REG_SEL_MUX2		2
#define CRM0_MUX_CTRL_REG_SEL_MUX2_LEN	1
#define CRM0_CLK_DIV_REG_CLK_DIV		0
#define CRM0_CLK_DIV_REG_CLK_DIV_LEN	2
#define CRM0_ROSC_DIV_REG_ROSC_DIV		0
#define CRM0_ROSC_DIV_REG_ROSC_DIV_LEN	2

volatile unsigned int * crm0_MUX_CTRL_REG	= (volatile unsigned int *) CRM0_MUX_CTRL_REG_ADDR;
volatile unsigned int * crm0_CLK_DIV_REG	= (volatile unsigned int *) CRM0_CLK_DIV_REG_ADDR;
volatile unsigned int * crm0_ROSC_DIV_REG	= (volatile unsigned int *) CRM0_ROSC_DIV_REG_ADDR;
